server:
  port: 8081

aliyun:
  oss:
    endpoint: http://oss-cn-shenzhen.aliyuncs.com
    accessKeyId: ****************
    accessKeySecret: ****************
    bucketName: ****************

logging:
  level:
    root: INFO
  file:
    name: isdp.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


